import { SelectOption } from '@/components/ui/SelectSearchInput';

export const COUNTRIES: SelectOption[] = [
  { value: 'KR', label: 'South Korea (대한민국)' },
  { value: 'US', label: 'United States (미국)' },
  { value: 'JP', label: 'Japan (일본)' },
  { value: 'CN', label: 'China (중국)' },
  { value: 'TW', label: 'Taiwan (대만)' },
  { value: 'HK', label: 'Hong Kong (홍콩)' },
  { value: 'VN', label: 'Vietnam (베트남)' },
  { value: 'TH', label: 'Thailand (태국)' },
  { value: 'PH', label: 'Philippines (필리핀)' },
  { value: 'ID', label: 'Indonesia (인도네시아)' },
  { value: 'MY', label: 'Malaysia (말레이시아)' },
  { value: 'SG', label: 'Singapore (싱가포르)' },
  { value: 'IN', label: 'India (인도)' },
  { value: 'PK', label: 'Pakistan (파키스탄)' },
  { value: 'BD', label: 'Bangladesh (방글라데시)' },
  { value: 'NP', label: 'Nepal (네팔)' },
  { value: 'LK', label: 'Sri Lanka (스리랑카)' },
  { value: 'MM', label: 'Myanmar (미얀마)' },
  { value: 'KH', label: 'Cambodia (캄보디아)' },
  { value: 'LA', label: 'Laos (라오스)' },
  { value: 'MN', label: 'Mongolia (몽골)' },
  { value: 'KZ', label: 'Kazakhstan (카자흐스탄)' },
  { value: 'UZ', label: 'Uzbekistan (우즈베키스탄)' },
  { value: 'GB', label: 'United Kingdom (영국)' },
  { value: 'DE', label: 'Germany (독일)' },
  { value: 'FR', label: 'France (프랑스)' },
  { value: 'IT', label: 'Italy (이탈리아)' },
  { value: 'ES', label: 'Spain (스페인)' },
  { value: 'NL', label: 'Netherlands (네덜란드)' },
  { value: 'BE', label: 'Belgium (벨기에)' },
  { value: 'CH', label: 'Switzerland (스위스)' },
  { value: 'AT', label: 'Austria (오스트리아)' },
  { value: 'SE', label: 'Sweden (스웨덴)' },
  { value: 'NO', label: 'Norway (노르웨이)' },
  { value: 'DK', label: 'Denmark (덴마크)' },
  { value: 'FI', label: 'Finland (핀란드)' },
  { value: 'PL', label: 'Poland (폴란드)' },
  { value: 'RU', label: 'Russia (러시아)' },
  { value: 'UA', label: 'Ukraine (우크라이나)' },
  { value: 'CA', label: 'Canada (캐나다)' },
  { value: 'MX', label: 'Mexico (멕시코)' },
  { value: 'BR', label: 'Brazil (브라질)' },
  { value: 'AR', label: 'Argentina (아르헨티나)' },
  { value: 'CL', label: 'Chile (칠레)' },
  { value: 'AU', label: 'Australia (호주)' },
  { value: 'NZ', label: 'New Zealand (뉴질랜드)' },
  { value: 'ZA', label: 'South Africa (남아프리카공화국)' },
  { value: 'EG', label: 'Egypt (이집트)' },
  { value: 'AE', label: 'UAE (아랍에미리트)' },
  { value: 'SA', label: 'Saudi Arabia (사우디아라비아)' },
  { value: 'TR', label: 'Turkey (터키)' },
  { value: 'IL', label: 'Israel (이스라엘)' },
];
