import { SelectOption } from '@/components/ui/SelectSearchInput';

export interface Country {
  id: number;
  name: string;
  code: string;
}

// 전체 국가 목록 (id, name, code 형식)
export const COUNTRIES_FULL: Country[] = [
  { id: 1, name: 'Andorra(안도라)', code: 'AD' },
  { id: 2, name: 'United Arab Emirates(아랍에미리트)', code: 'AE' },
  { id: 3, name: 'Afghanistan(아프가니스탄)', code: 'AF' },
  { id: 4, name: 'Antigua and Barbuda(앤티가 바부다)', code: 'AG' },
  { id: 5, name: 'Anguilla(앵귈라)', code: 'AI' },
  { id: 6, name: 'Albania(알바니아)', code: 'AL' },
  { id: 7, name: 'Armenia(아르메니아)', code: 'AM' },
  { id: 8, name: 'Angola(앙골라)', code: 'AO' },
  { id: 9, name: 'Antarctica(남극 대륙)', code: 'AQ' },
  { id: 10, name: 'Argentina(아르헨티나)', code: 'AR' },
  { id: 11, name: 'American Samoa(아메리칸 사모아)', code: 'AS' },
  { id: 12, name: 'Austria(오스트리아)', code: 'AT' },
  { id: 13, name: 'Australia(오스트레일리아)', code: 'AU' },
  { id: 14, name: 'Aruba(아루바)', code: 'AW' },
  { id: 15, name: 'Åland Islands(올란드 제도)', code: 'AX' },
  { id: 16, name: 'Azerbaijan(아제르바이잔)', code: 'AZ' },
  { id: 17, name: 'Bosnia and Herzegovina(보스니아 헤르체고비나)', code: 'BA' },
  { id: 18, name: 'Barbados(바베이도스)', code: 'BB' },
  { id: 19, name: 'Bangladesh(방글라데시)', code: 'BD' },
  { id: 20, name: 'Belgium(벨기에)', code: 'BE' },
  { id: 21, name: 'Burkina Faso(부르키나파소)', code: 'BF' },
  { id: 22, name: 'Bulgaria(불가리아)', code: 'BG' },
  { id: 23, name: 'Bahrain(바레인)', code: 'BH' },
  { id: 24, name: 'Burundi(부룬디)', code: 'BI' },
  { id: 25, name: 'Benin(베냉)', code: 'BJ' },
  { id: 26, name: 'Saint Barthélemy(생바르텔레미)', code: 'BL' },
  { id: 27, name: 'Bermuda(버뮤다)', code: 'BM' },
  { id: 28, name: 'Brunei Darussalam(브루나이)', code: 'BN' },
  { id: 29, name: 'Bolivia(볼리비아)', code: 'BO' },
  { id: 30, name: 'Bonaire, Sint Eustatius and Saba(네덜란드령 카리브)', code: 'BQ' },
  { id: 31, name: 'Brazil(브라질)', code: 'BR' },
  { id: 32, name: 'Bahamas(바하마)', code: 'BS' },
  { id: 33, name: 'Bhutan(부탄)', code: 'BT' },
  { id: 34, name: 'Bouvet Island(부베섬)', code: 'BV' },
  { id: 35, name: 'Botswana(보츠와나)', code: 'BW' },
  { id: 36, name: 'Belarus(벨라루스)', code: 'BY' },
  { id: 37, name: 'Belize(벨리즈)', code: 'BZ' },
  { id: 38, name: 'Canada(캐나다)', code: 'CA' },
  { id: 39, name: 'Cocos Islands(코코스 제도)', code: 'CC' },
  { id: 40, name: 'DR Congo(콩고-킨샤사)', code: 'CD' },
  { id: 41, name: 'Central African Republic(중앙 아프리카 공화국)', code: 'CF' },
  { id: 42, name: 'Congo(콩고-브라자빌)', code: 'CG' },
  { id: 43, name: 'Switzerland(스위스)', code: 'CH' },
  { id: 44, name: 'Côte d\'Ivoire(코트디부아르)', code: 'CI' },
  { id: 45, name: 'Cook Islands(쿡 제도)', code: 'CK' },
  { id: 46, name: 'Chile(칠레)', code: 'CL' },
  { id: 47, name: 'Cameroon(카메룬)', code: 'CM' },
  { id: 48, name: 'China(중국)', code: 'CN' },
  { id: 49, name: 'Colombia(콜롬비아)', code: 'CO' },
  { id: 50, name: 'Costa Rica(코스타리카)', code: 'CR' },
  { id: 51, name: 'Cuba(쿠바)', code: 'CU' },
  { id: 52, name: 'Cape Verde(카보베르데)', code: 'CV' },
  { id: 53, name: 'Curacao(퀴라소)', code: 'CW' },
  { id: 54, name: 'Christmas Island(크리스마스섬)', code: 'CX' },
  { id: 55, name: 'Cyprus(키프로스)', code: 'CY' },
  { id: 56, name: 'Czechia(체코)', code: 'CZ' },
  { id: 57, name: 'Germany(독일)', code: 'DE' },
  { id: 58, name: 'Djibouti(지부티)', code: 'DJ' },
  { id: 59, name: 'Denmark(덴마크)', code: 'DK' },
  { id: 60, name: 'Dominica(도미니카)', code: 'DM' },
  { id: 61, name: 'Dominican Republic(도미니카 공화국)', code: 'DO' },
  { id: 62, name: 'Algeria(알제리)', code: 'DZ' },
  { id: 63, name: 'Ecuador(에콰도르)', code: 'EC' },
  { id: 64, name: 'Estonia(에스토니아)', code: 'EE' },
  { id: 65, name: 'Egypt(이집트)', code: 'EG' },
  { id: 66, name: 'Western Sahara(서사하라)', code: 'EH' },
  { id: 67, name: 'Eritrea(에리트레아)', code: 'ER' },
  { id: 68, name: 'Spain(스페인)', code: 'ES' },
  { id: 69, name: 'Ethiopia(에티오피아)', code: 'ET' },
  { id: 70, name: 'Finland(핀란드)', code: 'FI' },
  { id: 71, name: 'Fiji(피지)', code: 'FJ' },
  { id: 72, name: 'Falkland Islands(포클랜드 제도)', code: 'FK' },
  { id: 73, name: 'Micronesia(미크로네시아)', code: 'FM' },
  { id: 74, name: 'Faroe Islands(페로 제도)', code: 'FO' },
  { id: 75, name: 'France(프랑스)', code: 'FR' },
  { id: 76, name: 'Gabon(가봉)', code: 'GA' },
  { id: 77, name: 'United Kingdom(영국)', code: 'GB' },
  { id: 78, name: 'Grenada(그레나다)', code: 'GD' },
  { id: 79, name: 'Georgia(조지아)', code: 'GE' },
  { id: 80, name: 'French Guiana(프랑스령 기아나)', code: 'GF' },
  { id: 81, name: 'Guernsey(건지)', code: 'GG' },
  { id: 82, name: 'Ghana(가나)', code: 'GH' },
  { id: 83, name: 'Gibraltar(지브롤터)', code: 'GI' },
  { id: 84, name: 'Greenland(그린란드)', code: 'GL' },
  { id: 85, name: 'Gambia(감비아)', code: 'GM' },
  { id: 86, name: 'Guinea(기니)', code: 'GN' },
  { id: 87, name: 'Guadeloupe(과들루프)', code: 'GP' },
  { id: 88, name: 'Equatorial Guinea(적도 기니)', code: 'GQ' },
  { id: 89, name: 'Greece(그리스)', code: 'GR' },
  { id: 90, name: 'South Georgia and the South Sandwich Islands(사우스조지아 사우스샌드위치 제도)', code: 'GS' },
  { id: 91, name: 'Guatemala(과테말라)', code: 'GT' },
  { id: 92, name: 'Guam(괌)', code: 'GU' },
  { id: 93, name: 'Guinea-Bissau(기니비사우)', code: 'GW' },
  { id: 94, name: 'Guyana(가이아나)', code: 'GY' },
  { id: 95, name: 'Hong Kong(홍콩(중국 특별행정구))', code: 'HK' },
  { id: 96, name: 'Heard Island and McDonald Islands(허드 맥도널드 제도)', code: 'HM' },
  { id: 97, name: 'Honduras(온두라스)', code: 'HN' },
  { id: 98, name: 'Croatia(크로아티아)', code: 'HR' },
  { id: 99, name: 'Haiti(아이티)', code: 'HT' },
  { id: 100, name: 'Hungary(헝가리)', code: 'HU' },
  { id: 101, name: 'Indonesia(인도네시아)', code: 'ID' },
  { id: 102, name: 'Ireland(아일랜드)', code: 'IE' },
  { id: 103, name: 'Israel(이스라엘)', code: 'IL' },
  { id: 104, name: 'Isle of Man(맨섬)', code: 'IM' },
  { id: 105, name: 'India(인도)', code: 'IN' },
  { id: 106, name: 'British Indian Ocean Territory(영국령 인도양 지역)', code: 'IO' },
  { id: 107, name: 'Iraq(이라크)', code: 'IQ' },
  { id: 108, name: 'Iran(이란)', code: 'IR' },
  { id: 109, name: 'Iceland(아이슬란드)', code: 'IS' },
  { id: 110, name: 'Italy(이탈리아)', code: 'IT' },
  { id: 111, name: 'Jersey(저지)', code: 'JE' },
  { id: 112, name: 'Jamaica(자메이카)', code: 'JM' },
  { id: 113, name: 'Jordan(요르단)', code: 'JO' },
  { id: 114, name: 'Japan(일본)', code: 'JP' },
  { id: 115, name: 'Kenya(케냐)', code: 'KE' },
  { id: 116, name: 'Kyrgyzstan(키르기스스탄)', code: 'KG' },
  { id: 117, name: 'Cambodia(캄보디아)', code: 'KH' },
  { id: 118, name: 'Kiribati(키리바시)', code: 'KI' },
  { id: 119, name: 'Comoros(코모로)', code: 'KM' },
  { id: 120, name: 'Saint Kitts and Nevis(세인트키츠 네비스)', code: 'KN' },
  { id: 121, name: 'North Korea(북한)', code: 'KP' },
  { id: 122, name: 'South Korea(대한민국)', code: 'KR' },
  { id: 123, name: 'Kuwait(쿠웨이트)', code: 'KW' },
  { id: 124, name: 'Cayman Islands(케이맨 제도)', code: 'KY' },
  { id: 125, name: 'Kazakhstan(카자흐스탄)', code: 'KZ' },
  { id: 126, name: 'Laos(라오스)', code: 'LA' },
  { id: 127, name: 'Lebanon(레바논)', code: 'LB' },
  { id: 128, name: 'Saint Lucia(세인트루시아)', code: 'LC' },
  { id: 129, name: 'Liechtenstein(리히텐슈타인)', code: 'LI' },
  { id: 130, name: 'Sri Lanka(스리랑카)', code: 'LK' },
  { id: 131, name: 'Liberia(라이베리아)', code: 'LR' },
  { id: 132, name: 'Lesotho(레소토)', code: 'LS' },
  { id: 133, name: 'Lithuania(리투아니아)', code: 'LT' },
  { id: 134, name: 'Luxembourg(룩셈부르크)', code: 'LU' },
  { id: 135, name: 'Latvia(라트비아)', code: 'LV' },
  { id: 136, name: 'Libya(리비아)', code: 'LY' },
  { id: 137, name: 'Morocco(모로코)', code: 'MA' },
  { id: 138, name: 'Monaco(모나코)', code: 'MC' },
  { id: 139, name: 'Moldova(몰도바)', code: 'MD' },
  { id: 140, name: 'Montenegro(몬테네그로)', code: 'ME' },
  { id: 141, name: 'Saint Martin(생마르탱)', code: 'MF' },
  { id: 142, name: 'Madagascar(마다가스카르)', code: 'MG' },
  { id: 143, name: 'Marshall Islands(마셜 제도)', code: 'MH' },
  { id: 144, name: 'North Macedonia(북마케도니아)', code: 'MK' },
  { id: 145, name: 'Mali(말리)', code: 'ML' },
  { id: 146, name: 'Myanmar(미얀마)', code: 'MM' },
  { id: 147, name: 'Mongolia(몽골)', code: 'MN' },
  { id: 148, name: 'Macao(마카오(중국 특별행정구))', code: 'MO' },
  { id: 149, name: 'Northern Mariana Islands(북마리아나제도)', code: 'MP' },
  { id: 150, name: 'Martinique(마르티니크)', code: 'MQ' },
  { id: 151, name: 'Mauritania(모리타니)', code: 'MR' },
  { id: 152, name: 'Montserrat(몬트세라트)', code: 'MS' },
  { id: 153, name: 'Malta(몰타)', code: 'MT' },
  { id: 154, name: 'Mauritius(모리셔스)', code: 'MU' },
  { id: 155, name: 'Maldives(몰디브)', code: 'MV' },
  { id: 156, name: 'Malawi(말라위)', code: 'MW' },
  { id: 157, name: 'Mexico(멕시코)', code: 'MX' },
  { id: 158, name: 'Malaysia(말레이시아)', code: 'MY' },
  { id: 159, name: 'Mozambique(모잠비크)', code: 'MZ' },
  { id: 160, name: 'Namibia(나미비아)', code: 'NA' },
  { id: 161, name: 'New Caledonia(누벨칼레도니)', code: 'NC' },
  { id: 162, name: 'Niger(니제르)', code: 'NE' },
  { id: 163, name: 'Norfolk Island(노퍽섬)', code: 'NF' },
  { id: 164, name: 'Nigeria(나이지리아)', code: 'NG' },
  { id: 165, name: 'Nicaragua(니카라과)', code: 'NI' },
  { id: 166, name: 'Netherlands(네덜란드)', code: 'NL' },
  { id: 167, name: 'Norway(노르웨이)', code: 'NO' },
  { id: 168, name: 'Nepal(네팔)', code: 'NP' },
  { id: 169, name: 'Nauru(나우루)', code: 'NR' },
  { id: 170, name: 'Niue(니우에)', code: 'NU' },
  { id: 171, name: 'New Zealand(뉴질랜드)', code: 'NZ' },
  { id: 172, name: 'Oman(오만)', code: 'OM' },
  { id: 173, name: 'Panama(파나마)', code: 'PA' },
  { id: 174, name: 'Peru(페루)', code: 'PE' },
  { id: 175, name: 'French Polynesia(프랑스령 폴리네시아)', code: 'PF' },
  { id: 176, name: 'Papua New Guinea(파푸아뉴기니)', code: 'PG' },
  { id: 177, name: 'Philippines(필리핀)', code: 'PH' },
  { id: 178, name: 'Pakistan(파키스탄)', code: 'PK' },
  { id: 179, name: 'Poland(폴란드)', code: 'PL' },
  { id: 180, name: 'Saint Pierre and Miquelon(생피에르 미클롱)', code: 'PM' },
  { id: 181, name: 'Pitcairn(핏케언 제도)', code: 'PN' },
  { id: 182, name: 'Puerto Rico(푸에르토리코)', code: 'PR' },
  { id: 183, name: 'Palestine, State of(팔레스타인)', code: 'PS' },
  { id: 184, name: 'Portugal(포르투갈)', code: 'PT' },
  { id: 185, name: 'Palau(팔라우)', code: 'PW' },
  { id: 186, name: 'Paraguay(파라과이)', code: 'PY' },
  { id: 187, name: 'Qatar(카타르)', code: 'QA' },
  { id: 188, name: 'Reunion(레위니옹)', code: 'RE' },
  { id: 189, name: 'Romania(루마니아)', code: 'RO' },
  { id: 190, name: 'Serbia(세르비아)', code: 'RS' },
  { id: 191, name: 'Russia(러시아)', code: 'RU' },
  { id: 192, name: 'Rwanda(르완다)', code: 'RW' },
  { id: 193, name: 'Saudi Arabia(사우디아라비아)', code: 'SA' },
  { id: 194, name: 'Solomon Islands(솔로몬 제도)', code: 'SB' },
  { id: 195, name: 'Seychelles(세이셸)', code: 'SC' },
  { id: 196, name: 'Sudan(수단)', code: 'SD' },
  { id: 197, name: 'Sweden(스웨덴)', code: 'SE' },
  { id: 198, name: 'Singapore(싱가포르)', code: 'SG' },
  { id: 199, name: 'Saint Helena, Ascension and Tristan da Cunha(세인트헬레나)', code: 'SH' },
  { id: 200, name: 'Slovenia(슬로베니아)', code: 'SI' },
  { id: 201, name: 'Svalbard and Jan Mayen(스발바르제도-얀마웬섬)', code: 'SJ' },
  { id: 202, name: 'Slovakia(슬로바키아)', code: 'SK' },
  { id: 203, name: 'Sierra Leone(시에라리온)', code: 'SL' },
  { id: 204, name: 'San Marino(산마리노)', code: 'SM' },
  { id: 205, name: 'Senegal(세네갈)', code: 'SN' },
  { id: 206, name: 'Somalia(소말리아)', code: 'SO' },
  { id: 207, name: 'Suriname(수리남)', code: 'SR' },
  { id: 208, name: 'South Sudan(남수단)', code: 'SS' },
  { id: 209, name: 'Sao Tome and Principe(상투메 프린시페)', code: 'ST' },
  { id: 210, name: 'El Salvador(엘살바도르)', code: 'SV' },
  { id: 211, name: 'Sint Maarten(신트마르턴)', code: 'SX' },
  { id: 212, name: 'Syria(시리아)', code: 'SY' },
  { id: 213, name: 'Eswatini(에스와티니)', code: 'SZ' },
  { id: 214, name: 'Turks and Caicos Islands(터크스 케이커스 제도)', code: 'TC' },
  { id: 215, name: 'Chad(차드)', code: 'TD' },
  { id: 216, name: 'French Southern Territories(프랑스령 남방 지역)', code: 'TF' },
  { id: 217, name: 'Togo(토고)', code: 'TG' },
  { id: 218, name: 'Thailand(태국)', code: 'TH' },
  { id: 219, name: 'Tajikistan(타지키스탄)', code: 'TJ' },
  { id: 220, name: 'Tokelau(토켈라우)', code: 'TK' },
  { id: 221, name: 'Timor-Leste(동티모르)', code: 'TL' },
  { id: 222, name: 'Turkmenistan(투르크메니스탄)', code: 'TM' },
  { id: 223, name: 'Tunisia(튀니지)', code: 'TN' },
  { id: 224, name: 'Tonga(통가)', code: 'TO' },
  { id: 225, name: 'Turkey(튀르키예)', code: 'TR' },
  { id: 226, name: 'Trinidad and Tobago(트리니다드 토바고)', code: 'TT' },
  { id: 227, name: 'Tuvalu(투발루)', code: 'TV' },
  { id: 228, name: 'Taiwan(대만)', code: 'TW' },
  { id: 229, name: 'Tanzania(탄자니아)', code: 'TZ' },
  { id: 230, name: 'Ukraine(우크라이나)', code: 'UA' },
  { id: 231, name: 'Uganda(우간다)', code: 'UG' },
  { id: 232, name: 'United States Minor Outlying Islands(미국령 해외 제도)', code: 'UM' },
  { id: 233, name: 'United States(미국)', code: 'US' },
  { id: 234, name: 'Uruguay(우루과이)', code: 'UY' },
  { id: 235, name: 'Uzbekistan(우즈베키스탄)', code: 'UZ' },
  { id: 236, name: 'Vatican City(바티칸 시국)', code: 'VA' },
  { id: 237, name: 'Saint Vincent and the Grenadines(세인트빈센트그레나딘)', code: 'VC' },
  { id: 238, name: 'Venezuela(베네수엘라)', code: 'VE' },
  { id: 239, name: 'British Virgin Islands(영국령 버진아일랜드)', code: 'VG' },
  { id: 240, name: 'US Virgin Islands(미국령 버진아일랜드)', code: 'VI' },
  { id: 241, name: 'Vietnam(베트남)', code: 'VN' },
  { id: 242, name: 'Vanuatu(바누아투)', code: 'VU' },
  { id: 243, name: 'Wallis and Futuna(왈리스-푸투나 제도)', code: 'WF' },
  { id: 244, name: 'Samoa(사모아)', code: 'WS' },
  { id: 245, name: 'Yemen(예멘)', code: 'YE' },
  { id: 246, name: 'Mayotte(마요트)', code: 'YT' },
  { id: 247, name: 'South Africa(남아프리카)', code: 'ZA' },
  { id: 248, name: 'Zambia(잠비아)', code: 'ZM' },
  { id: 249, name: 'Zimbabwe(짐바브웨)', code: 'ZW' },
];

// SelectOption 형식으로 변환 (기존 호환성 유지)
export const COUNTRIES: SelectOption[] = COUNTRIES_FULL.map(country => ({
  value: country.code,
  label: country.name
}));
